// <auto-generated />
using System;
using ForNewTest.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForNewTest.Migrations
{
    [DbContext(typeof(AplicationDBContext))]
    partial class AplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ForNewTest.Entidades.ActorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Foto")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Actores");
                });

            modelBuilder.Entity("ForNewTest.Entidades.ActorPelicula", b =>
                {
                    b.Property<int>("PeliculaModelId")
                        .HasColumnType("int");

                    b.Property<int>("ActorModelId")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Personaje")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PeliculaModelId", "ActorModelId");

                    b.HasIndex("ActorModelId");

                    b.ToTable("ActorPeliculas");
                });

            modelBuilder.Entity("ForNewTest.Entidades.ComentarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cuerpo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PeliculaModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PeliculaModelId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("ForNewTest.Entidades.ErrorModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("MensajeError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Errores");
                });

            modelBuilder.Entity("ForNewTest.Entidades.GeneroModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("ForNewTest.Entidades.GeneroPelicula", b =>
                {
                    b.Property<int>("PeliculaModelId")
                        .HasColumnType("int");

                    b.Property<int>("GeneroModelId")
                        .HasColumnType("int");

                    b.HasKey("PeliculaModelId", "GeneroModelId");

                    b.HasIndex("GeneroModelId");

                    b.ToTable("GeneroPeliculas");
                });

            modelBuilder.Entity("ForNewTest.Entidades.PeliculaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EnCines")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaLanzamiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Poster")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Peliculas");
                });

            modelBuilder.Entity("ForNewTest.Entidades.ActorPelicula", b =>
                {
                    b.HasOne("ForNewTest.Entidades.ActorModel", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForNewTest.Entidades.PeliculaModel", "Pelicula")
                        .WithMany("ActoresPeliculas")
                        .HasForeignKey("PeliculaModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Pelicula");
                });

            modelBuilder.Entity("ForNewTest.Entidades.ComentarioModel", b =>
                {
                    b.HasOne("ForNewTest.Entidades.PeliculaModel", null)
                        .WithMany("Comentarios")
                        .HasForeignKey("PeliculaModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForNewTest.Entidades.GeneroPelicula", b =>
                {
                    b.HasOne("ForNewTest.Entidades.GeneroModel", "Genero")
                        .WithMany("GeneroPeliculas")
                        .HasForeignKey("GeneroModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForNewTest.Entidades.PeliculaModel", "Pelicula")
                        .WithMany("GeneroPeliculas")
                        .HasForeignKey("PeliculaModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");

                    b.Navigation("Pelicula");
                });

            modelBuilder.Entity("ForNewTest.Entidades.GeneroModel", b =>
                {
                    b.Navigation("GeneroPeliculas");
                });

            modelBuilder.Entity("ForNewTest.Entidades.PeliculaModel", b =>
                {
                    b.Navigation("ActoresPeliculas");

                    b.Navigation("Comentarios");

                    b.Navigation("GeneroPeliculas");
                });
#pragma warning restore 612, 618
        }
    }
}
